Make pre-commit script more user friendly

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,11 +1,18 @@
 #!/usr/bin/env bash
-# Regenerates documentaion and adds it to the commit
+# Regenerates documentation and adds it to the commit
 #
-echo
+echo "-- pre-commit script: Generate documentation --"
+APIGEN='vendor/bin/apigen'
+if ! [[ -f $APIGEN && -x $APIGEN ]]
+then
+    echo "Cannot find APIGen in vendor folder. Have you run 'composer install'?"
+    exit 1
+fi
+
 echo "Regenerating Documentation..."
-vendor/bin/apigen -q generate
+$APIGEN -q generate
 echo "Regeneration complete!"
 echo "Adding updated docs to commit"
 git add docs
 git add -u docs
-echo "All done!"
+echo "-- pre-commit script: All done! --"
